/*
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package io.typefox.yang


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class YangStandaloneSetup extends YangStandaloneSetupGenerated {

	def static void doSetup() {
		new YangStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
