/*
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package io.typefox.yang


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class YangRuntimeModule extends AbstractYangRuntimeModule {
}
