/*
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package io.typefox.yang.ide

import com.google.inject.Guice
import io.typefox.yang.YangRuntimeModule
import io.typefox.yang.YangStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class YangIdeSetup extends YangStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new YangRuntimeModule, new YangIdeModule))
	}
	
}
