/*
 * generated by Xtext 2.13.0-SNAPSHOT
 */
package io.typefox.yang.formatting2

import org.eclipse.xtext.formatting2.AbstractFormatter2
import org.eclipse.xtext.formatting2.IFormattableDocument

class YangFormatter extends AbstractFormatter2 {
	
	override format(Object obj, IFormattableDocument document) {
		throw new UnsupportedOperationException("TODO: auto-generated method stub")
	}
	
}
